# Generated by Django 5.0.2 on 2024-03-08 08:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="created on"),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modified on"
                    ),
                ),
                (
                    "profile_pictue",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user/profile/",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "library_card_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Library Card No."
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Address")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone No."),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("gender", models.CharField(max_length=10, verbose_name="Gender")),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
