# Generated by Django 5.0.8 on 2025-01-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_otp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email']},
        ),
        migrations.AlterModelOptions(
            name='customusergroup',
            options={'ordering': ['name'], 'verbose_name': 'group', 'verbose_name_plural': 'groups'},
        ),
    ]
