# Generated by Django 5.0.2 on 2024-03-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_borrow"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="borrower",
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
