# Generated by Django 5.0.2 on 2024-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_remove_book_borrower_book_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("Available", "Available"),
                    ("Reserved", "Reserved"),
                    ("Unavailable", "Unavailable"),
                ],
                default="Available",
                max_length=11,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=17),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("title", "isbn")},
        ),
    ]
