# Generated by Django 5.0.2 on 2024-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_availability_status_alter_book_isbn_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrow",
            name="borrow_status",
            field=models.CharField(
                choices=[("Not Returned", "Not Returned"), ("Returned", "Returned")],
                default="Not Returned",
                max_length=12,
            ),
        ),
    ]
