# Generated by Django 5.0.2 on 2024-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_book_publication_year_alter_book_availability_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserve",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
