# Generated by Django 5.0.3 on 2024-08-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
