# Generated by Django 5.0.8 on 2024-09-02 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
