# Generated by Django 5.0.8 on 2024-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_book_section_book_shelf_alter_genre_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_on']},
        ),
    ]
