# Generated by Django 5.0.8 on 2024-09-02 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0015_delete_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'pdf'), ('interactive', 'Interactive')], max_length=11)),
                ('file', models.FileField(upload_to='digital_resources/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('related_books', models.ManyToManyField(blank=True, related_name='digital_resources', to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
